### ISSUE TITLE
Roadmap 🚲

### ISSUE THREAD

**Issue by Allicolyer** [georgemandis/recurse-roulette-server#1]
## Project Scope

**MVP - Minimum Viable Product**
- RC people can authenticate
- Users can be randomly matched to video chat 
- If there is an odd number of users - wait until another person joins, otherwise, you'll get a match

**Future Features**
- Users can be “online”
- Mysterious Virtual Avatar instead of your picture
- Not being paired with people you have already been paired with

**Potential Use Cases** 

- Coffee chats
- Lunch chats
- First day of RC pairing 
- RC speed dating 

##  Implementation

**Signalling Server** 

- Keeps track of available peers
- Matches peers
- Built using Express

**Client**

- Makes the p2p connection with another client
- Built using React or JS Classic

**Tools**

- [Webrtc](https://webrtc.org/) - allows you to make peer to peer connection on the client-side
- [Peer.js](https://peerjs.com/) allows you to use WebRTC, also, [npm package](https://www.npmjs.com/package/peerjs)
- [Using Firebase with WEBRTC](https://webrtc.org/getting-started/firebase-rtc-codelab)

**Considerations**
- Where do we keep track of who is connected?
- Only RC people can use this 
      - We will use RC’s OAuth API
- Possibility to use Salman’s signaling server
    - We’ll use Express for now
- Hosting
    - Glitch, now, Heroku, just to name a few…..
- Waiting Room Model vs instant pairing Model 
- Events that can happen on the client side
    1. Go make a connection to another peer with Peer ID
    2. Peer is trying to make a connection with Peer ID

## Dream team 🦸‍♀️🦸‍♂️
Team A - Alli (@allicolyer) && Asa(@asaneedle)
Team Beard - George (@georgemandis) && Sam (@samson212 )

**Comment by georgemandis** [comment]
Closing this out because I moved it to the wiki:
[https://github.com/georgemandis/recurse-roulette-server/wiki/Roadmap-%F0%9F%9A%B2](https://github.com/georgemandis/recurse-roulette-server/wiki/Roadmap-%F0%9F%9A%B2)
