### ISSUE TITLE
RC Session Roulette Feedback

### ISSUE THREAD

**Issue by Allicolyer** [georgemandis/recurse-roulette-server#16]
**Things to fix**
- Bad connections lead to dropped calls
- Things on firefox don't seem to work as well

**Eavesdropping bug** 
- Sometimes a connection isn't closed on both ends
- Dylan had a bug with too many peer connections open
- Potentially relevant issues
    - https://github.com/peers/peerjs/issues/636 
    -  https://github.com/peers/peerjs/issues/565 
- More theories
  - call event getting fired before hangup event
  - move line 195 `peerCall = call;`
  - the asynchronous `await fetch(`/api/peers/consume/${myPeerID}`);` could be causing issues
  - `peerCon` is misspelt
  - there should be more checks to make sure that incoming calls are thrown in the trash 

**Takeaways from debugging session**
- Listen for an error event and disconnect events
- Be more diligent about destroying connections
- Be more diligent about checking for previous connections before making new ones.
- Less emphasis on event listeners, more emphasis on if objects exist
- Create a hangup data event that gets sent to the connected peer

**Feedback**
- Feature request for a timer

**Comment by georgemandis** [comment]
Closing this out because I moved it to the Wiki:
[https://github.com/georgemandis/recurse-roulette-server/wiki/RC-Session-Roulette-Feedback](https://github.com/georgemandis/recurse-roulette-server/wiki/RC-Session-Roulette-Feedback)
