### ISSUE TITLE
Bugs to fix 

### ISSUE THREAD

**Issue by Allicolyer** [georgemandis/recurse-roulette-server#30]
Small bugs
- Name tags do not consistently clear
- You cannot leave the rotation if you are not in a call
- ~~Have separate time for when this session ends~~
- ~~Upload a favicon already~~
- Provide option to select which webcam you use
- ~~Add Wesley's turning background red:~~
```window.setInterval(function() { if ((document.getElementById("timeToNextRound").innerHTML.slice(0,2) + document.getElementById("timeToNextRound").innerHTML.slice(3,5)) < 45) {document.body.style.background = "red";} else {document.body.style.background = "white";}}, 1000)```

Bigger bugs
- Spying bug still exists
- Getting kicked out if your connection drops without rejoining

**Comment by georgemandis** [comment]
We probably should break each of these out into their own issue so we can close them out with future PRs.

**Comment by georgemandis** [comment]
Moved individual items into their own issue.
