### ISSUE TITLE
Show previous matches in client

### ISSUE THREAD

**Issue by georgemandis** [georgemandis/recurse-roulette-server#32]
Show some kind of list of people you’ve already paired with in the client? Just names.

**Comment by Allicolyer** [comment]
Could we do this with localStorage?

**Comment by georgemandis** [comment]
If we want the list to persist after a refresh that would be a good solution. We'd probably want to have something that clears this list every 24 hours or so. 

Or alternatively use cookies, which would take care of that refresh part for us, but localStorage has a nicer API to work with, in my opinion.
