### ISSUE TITLE
Feature: add fun effects!

### ISSUE THREAD

**Issue by georgemandis** [georgemandis/recurse-roulette-server#7]
Maybe we could leverage CSS Filters + Blend Modes to create fun effects for people in the conversation?

[https://developer.mozilla.org/en-US/docs/Web/CSS/filter](https://developer.mozilla.org/en-US/docs/Web/CSS/filter)
[https://css-tricks.com/basics-css-blend-modes/](https://css-tricks.com/basics-css-blend-modes/)

I think the approach to take would be to send "data" over the peer connection letting the other participant know which combination of filters/blend modes they're applying to themselves and recreating that in the client.

It's browser-dependent obviously, but I don't think it would be wildly hard to create something approximating the Zoom background effect using a combination of blend modes and filters.

**Comment by Allicolyer** [comment]
All for the fun effects! Maybe I can get the connection event working on #6 and we can use that to send the filter data?

**Comment by georgemandis** [comment]
After exploration, I think maybe this might make more sense as a separate/different project. The chat roulette feature seems pretty perfect on its own.
